# Generated by Django 3.0.3 on 2020-02-22 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.FloatField()),
                ('sale', models.FloatField()),
                ('start_date', models.DateField(blank=True, default=django.utils.datetime_safe.date.today, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencylist.CurrencyDictionary')),
            ],
        ),
    ]
